services:
  - type: web
    name: booking-agent-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
  - type: web
    name: booking-employee-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn employee_dashboard.app:app
